runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/app/index.html
  upload: dist/app/index.html
- url: /
  static_dir: dist/app
skip_files: 
  - e2e/
  - node_modules/
  - src/
  - coverage/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE$
